services:
  saps-dashboard:
    build:
      args: {}
      context: .
      dockerfile: ./docker/Dockerfile
    command: sleep 6000000
    image: eoscsynergyapps/saps-dashboard:sqaaas
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  saps-dashboard-docs:
    command: sleep 6000000
    image: sphinxdoc/sphinx
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  saps-hadolint:
    command: sleep 6000000
    image: hadolint/hadolint:latest-alpine
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
